package constants

const Select = "select "
const Where = " where "
const And = " and "
const Or = " or "
const Asteric = " * "
const From = " from "
const Like = " like "
const NotLike = " not like "
const OrderBy = " order by "
const Ascending = " asc "
const Descending = " desc "
const Limit = " limit "
const GroupBy = " group by "
const Having = " having "
const Greater = " > "
const Lesser = " < "
const Between = " between "
const NotEqual = " <> "
